version: "3.7"
services:
  api:
    container_name: api
    environment:
      DB_MASTER_HOST: db
      DB_MASTER_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: 'Asia/Tokyo'
    volumes:
      - ./api/:/api
    working_dir:
      /api
    ports:
      - "8080:8080"
      - "10206:10206" # for debug
    stdin_open: true
    tty: true
    build:
      context: api
    depends_on:
      - db
    networks:
      - project-template-net
  db:
    image: postgres:15.2
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: 'UTC'
    command: postgres -c listen_addresses='*'
    ports:
      - "15432:5432"
    networks:
      - project-template-net
  front:
    container_name: front
    image: node:18-alpine
    volumes:
      - ./front/:/front
    working_dir: /front
    command: >
      sh -c 'npm config set legacy-peer-deps true &&
      npm i &&
      npm install && npm run dev'
    ports:
      - '5173:5173'
    networks:
      - project-template-net
networks:
  project-template-net:
    driver: bridge